# action.yml

name: 'PP tool'
description: 'fast image comparison tool for devs by devs'
inputs:
  who-are-you:
    description: 'Who are you?'
    required: true
    default: 'Bro'
 outputs:
   time:
     description: 'The time when you run this action'
 runs:
   using: 'docker'
   image: 'Dockerfile'
   args:
     - ${{ inputs.who-are-you }}
